import {match,mc,multi,num,order,tf} from '../question-bank/helpers.mjs'

export const aiTopic4={
'SL 4.1':[
  mc('A school wants a sample containing students from every year group in proportion to year-group size. Which method is best?',['Convenience sampling','Stratified sampling','Voluntary response','Systematic sampling without strata'],'Stratified sampling','Stratification preserves representation from each relevant subgroup.',{tags:['sampling','stratified sampling']}),
  multi('Select all quantitative variables.',['Journey time','Number of messages sent','Favourite app','Type of transport'],['Journey time','Number of messages sent'],'Times and counts are numerical; favourite app and transport type are categorical.',{tags:['data types']}),
  tf('A very large convenience sample is guaranteed to be unbiased.',false,'A larger sample reduces random sampling variation but does not remove selection bias.',{questionStyle:'misconception',tags:['sampling bias']})],
'SL 4.2':[
  num('A box plot has lower quartile 17 and upper quartile 29. Find the interquartile range.',12,'IQR=Q₃−Q₁=29−17=12.',{tags:['box plots','interquartile range']}),
  mc('Which display is most suitable for comparing the medians and spreads of three groups?',['Pie charts','Side-by-side box plots','A scatter plot','A tree diagram'],'Side-by-side box plots','Box plots display median, quartiles and spread compactly for comparison.',{tags:['data presentation','box plots']}),
  tf('For unequal-width histogram classes, bar height should be frequency density so that area represents frequency.',true,'Frequency density corrects for different class widths.',{questionStyle:'conceptual',tags:['histograms','frequency density']})],
'SL 4.3':[
  num('Find the mean of 5, 7, 8, 8, 12.',8,'The sum is 40, so the mean is 40/5=8.',{tags:['mean']}),
  num('A dataset has standard deviation 4. Every value is multiplied by 3. Find the new standard deviation.',12,'Multiplying every value by 3 multiplies standard deviation by |3|.',{tags:['standard deviation','transformations']}),
  multi('Select all measures that are resistant to one extreme outlier.',['Median','Mean','Interquartile range','Range'],['Median','Interquartile range'],'Median and IQR depend mainly on order and central positions rather than extreme magnitudes.',{questionStyle:'conceptual',tags:['outliers','summary statistics']})],
'SL 4.4':[
  mc('Pearson’s correlation coefficient is r=−0.87. What does this indicate?',['Strong positive linear association','Strong negative linear association','Weak negative association','No association'],'Strong negative linear association','The magnitude is close to 1 and the sign is negative.',{tags:['Pearson correlation']}),
  num('A regression model is y=2.4x+7. Predict y when x=15.',43,'y=2.4(15)+7=43.',{tags:['regression','prediction']}),
  multi('Select all justified statements about correlation and regression.',['Correlation does not prove causation.','Extrapolation far beyond the data range can be unreliable.','An outlier can strongly affect Pearson’s r.','r=0 proves there is no relationship of any kind.'],['Correlation does not prove causation.','Extrapolation far beyond the data range can be unreliable.','An outlier can strongly affect Pearson’s r.'],'Pearson’s r measures linear association; a nonlinear relationship can have r near zero.',{questionStyle:'conceptual',tags:['correlation','interpretation']})],
'SL 4.5':[
  num('A fair six-sided die is rolled 90 times. Find the expected number of rolls greater than 4.',30,'P(roll>4)=2/6=1/3, so the expected count is 90/3=30.',{tags:['expected frequency']}),
  mc('If P(A)=0.28, find P(Aᶜ).',['0.28','0.72','1.28','Cannot be found'],'0.72','Complementary probabilities sum to 1.',{tags:['probability','complement']}),
  match('Match each experiment to the number of equally likely outcomes.',[{left:'One coin toss','right':'2'},{left:'Two coin tosses','right':'4'},{left:'One die roll and one coin toss','right':'12'}],'Multiply the number of choices at independent stages.',{questionStyle:'conceptual',tags:['sample spaces']})],
'SL 4.6':[
  mc('Events A and B satisfy P(A)=0.55, P(B)=0.40 and P(A∩B)=0.15. Find P(A∪B).',['0.15','0.65','0.80','1.10'],'0.80','P(A∪B)=0.55+0.40−0.15=0.80.',{tags:['probability rules']}),
  num('Given P(A∩B)=0.24 and P(B)=0.60, find P(A|B).',0.4,'P(A|B)=0.24/0.60=0.4.',{tags:['conditional probability']}),
  multi('P(A)=0.3, P(B)=0.5 and P(A∩B)=0.15. Select all true statements.',['A and B are independent.','A and B are mutually exclusive.','P(A∪B)=0.65.','P(A|B)=0.3.'],['A and B are independent.','P(A∪B)=0.65.','P(A|B)=0.3.'],'P(A)P(B)=0.15, the union is 0.65, and P(A|B)=0.15/0.5=0.3.',{questionStyle:'conceptual',tags:['independence','conditional probability']})],
'SL 4.7':[
  num('A random variable X has P(X=0)=0.25, P(X=1)=0.50 and P(X=4)=0.25. Find E(X).',1.5,'E(X)=0(0.25)+1(0.50)+4(0.25)=1.5.',{tags:['discrete random variables','expectation']}),
  mc('A probability distribution has probabilities 0.12, 0.31, k and 0.27. Find k.',['0.20','0.30','0.43','0.70'],'0.30','Probabilities sum to 1, so k=1−0.70=0.30.',{tags:['probability distributions']}),
  tf('The expected value of a discrete random variable must be a value that can occur in a single trial.',false,'Expectation is a long-run weighted mean and need not be an attainable outcome.',{questionStyle:'misconception',tags:['expected value']})],
'SL 4.8':[
  mc('Which scenario can be modelled by a binomial distribution?',['The number of sixes in 20 independent die rolls','The time until a bus arrives','Heights of 20 students','Sampling without replacement from 4 objects until empty'],'The number of sixes in 20 independent die rolls','There are fixed independent trials, two outcomes per trial and constant success probability.',{tags:['binomial distribution','conditions']}),
  num('For X~B(30,0.2), find E(X).',6,'The binomial mean is np=30(0.2)=6.',{tags:['binomial mean']}),
  num('For X~B(15,0.4), find Var(X).',3.6,'Variance=np(1−p)=15(0.4)(0.6)=3.6.',{questionStyle:'conceptual',tags:['binomial variance']})],
'SL 4.9':[
  mc('For a normal distribution, approximately what proportion lies within two standard deviations of the mean?',['0.50','0.68','0.95','0.997'],'0.95','The empirical rule gives about 95% within two standard deviations.',{tags:['normal distribution']}),
  num('For X~N(70,8²), find the z-score corresponding to X=86.',2,'z=(86−70)/8=2.',{tags:['normal distribution','standardization']}),
  tf('A normal distribution is symmetric, so its mean and median are equal.',true,'Symmetry about the centre makes the mean and median coincide.',{questionStyle:'conceptual',tags:['normal distribution','symmetry']})],
'SL 4.10':[
  mc('When is Spearman’s rank correlation generally more suitable than Pearson’s correlation?',['When the association is monotonic but not necessarily linear','Only when both variables are categorical','When there are no paired observations','Only when the sample size is exactly 10'],'When the association is monotonic but not necessarily linear','Spearman uses ranks and measures monotonic association.',{tags:['Spearman rank','method selection']}),
  num('Six paired observations have Σd²=14. Find Spearman’s rank coefficient using rₛ=1−6Σd²/[n(n²−1)], correct to three decimals.',0.6,'rₛ=1−84/[6(35)]=1−0.4=0.6.',{calculator:'allowed',tags:['Spearman rank','calculation']},0.001),
  multi('Select all true statements about Spearman’s rank coefficient.',['It is based on ranks.','Values near −1 indicate strong negative monotonic association.','It is usually less sensitive to extreme raw values than Pearson’s r.','It proves causation when |rₛ| is large.'],['It is based on ranks.','Values near −1 indicate strong negative monotonic association.','It is usually less sensitive to extreme raw values than Pearson’s r.'],'Ranking reduces the impact of raw magnitudes, but no correlation coefficient proves causation.',{questionStyle:'conceptual',tags:['Spearman rank','interpretation']})],
'SL 4.11':[
  mc('A test uses significance level 5% and gives p=0.032. What decision is made?',['Reject H₀','Fail to reject H₀','Accept H₀ as certainly true','Increase p to 0.05'],'Reject H₀','Since p<0.05, the result is statistically significant at the 5% level.',{tags:['hypothesis testing','p-value']}),
  mc('Which test is appropriate for checking whether observed category frequencies fit a stated distribution?',['Chi-square goodness-of-fit test','Pearson correlation','Two-sample t-test','Normal inverse calculation'],'Chi-square goodness-of-fit test','A goodness-of-fit test compares observed and expected categorical frequencies.',{tags:['chi-square','test selection']}),
  multi('Select all valid interpretations of a p-value of 0.08.',['At the 5% level, fail to reject H₀.','At the 10% level, reject H₀.','The probability that H₀ is true is exactly 0.08.','The result depends on the chosen significance level.'],['At the 5% level, fail to reject H₀.','At the 10% level, reject H₀.','The result depends on the chosen significance level.'],'Compare p with α; a p-value is not the probability that the null hypothesis is true.',{questionStyle:'conceptual',tags:['p-value','significance']})],
'AHL 4.12':[
  mc('Which design best tests whether a new teaching method causes improved scores?',['Randomly assign similar students to new and standard methods','Survey only volunteers using the new method','Compare this year with a different school last year','Ask students which method they prefer'],'Randomly assign similar students to new and standard methods','Random assignment helps balance confounders and supports causal inference.',{tags:['experimental design','randomization']}),
  multi('Select all features that improve a questionnaire study.',['Use neutral wording.','Pilot the questionnaire.','Use a representative sampling frame.','Ask two ideas in every question.'],['Use neutral wording.','Pilot the questionnaire.','Use a representative sampling frame.'],'Double-barrelled questions reduce clarity; neutral tested questions and representative sampling improve validity.',{tags:['questionnaires','data collection']}),
  tf('In an observational study, an association can be affected by confounding variables.',true,'Without controlled assignment, other variables may explain the observed association.',{questionStyle:'conceptual',tags:['observational studies','confounding']})],
'AHL 4.13':[
  mc('A residual plot shows a clear curved pattern. What does this suggest?',['The chosen regression form is inadequate','The model is certainly perfect','All residuals are zero','The response variable is categorical'],'The chosen regression form is inadequate','A systematic residual pattern indicates structure not captured by the model.',{tags:['residuals','model fit']}),
  num('A model has total sum of squares 250 and residual sum of squares 40. Find R².',0.84,'R²=1−40/250=0.84.',{tags:['coefficient of determination']},0.001),
  multi('Select all signs of a useful regression model.',['Residuals are randomly scattered around zero.','R² is high for the modelling context.','Predictions are used within a reasonable domain.','Every residual has the same positive sign.'],['Residuals are randomly scattered around zero.','R² is high for the modelling context.','Predictions are used within a reasonable domain.'],'Same-sign residuals indicate systematic bias rather than a well-centred fit.',{questionStyle:'conceptual',tags:['regression diagnostics','residuals']})],
'AHL 4.14':[
  num('If E(X)=12, find E(3X−5).',31,'E(3X−5)=3E(X)−5=36−5=31.',{tags:['random variables','expectation']}),
  num('If Var(X)=7, find Var(4X+2).',112,'Var(4X+2)=4²Var(X)=16(7)=112.',{tags:['variance','linear transformations']}),
  tf('Adding a constant c to every value of a random variable increases its variance by c.',false,'A shift changes the mean but not the spread, so variance is unchanged.',{questionStyle:'misconception',tags:['variance','transformations']})],
'AHL 4.15':[
  num('Independent normal variables X and Y have variances 9 and 16. Find Var(X+Y).',25,'For independent variables, variances add: 9+16=25.',{tags:['linear combinations','variance']}),
  mc('The central limit theorem is most useful for which statement?',['The sample mean is approximately normal for sufficiently large samples under broad conditions','Every population is exactly normal','Sample variance is always zero','All observations become independent'],'The sample mean is approximately normal for sufficiently large samples under broad conditions','The theorem concerns the distribution of sample means.',{tags:['central limit theorem']}),
  multi('Let X and Y be independent. Select all true statements.',['E(X+Y)=E(X)+E(Y).','Var(X−Y)=Var(X)+Var(Y).','SD(X+Y)=SD(X)+SD(Y) in every case.','A linear combination of normal variables is normal.'],['E(X+Y)=E(X)+E(Y).','Var(X−Y)=Var(X)+Var(Y).','A linear combination of normal variables is normal.'],'Independent variances add, but standard deviations do not generally add.',{questionStyle:'conceptual',tags:['linear combinations','normal variables']})],
'AHL 4.16':[
  mc('A 95% confidence interval for a mean is (42.1,47.9). Which interpretation is appropriate?',['The method captures the true mean in about 95% of repeated samples','95% of individual observations lie in this interval','The true mean changes between 42.1 and 47.9','There is a 95% chance every future value lies in the interval'],'The method captures the true mean in about 95% of repeated samples','Confidence refers to the long-run performance of the interval procedure.',{tags:['confidence intervals','interpretation']}),
  num('A confidence interval is written 18.4±2.1. Find its upper endpoint.',20.5,'Upper endpoint=18.4+2.1=20.5.',{tags:['confidence intervals']}),
  multi('Select all changes that generally make a confidence interval for a mean narrower.',['Increase the sample size.','Use a lower confidence level.','Reduce population variability.','Use a smaller sample size.'],['Increase the sample size.','Use a lower confidence level.','Reduce population variability.'],'More information and less variability reduce margin of error; higher confidence makes intervals wider.',{questionStyle:'conceptual',tags:['confidence intervals','precision']})],
'AHL 4.17':[
  mc('Which situation is suitable for a Poisson model?',['Number of calls arriving in one minute at a stable average rate','Heights of adults','Number of heads in exactly 10 coin tosses','Time taken by one runner'],'Number of calls arriving in one minute at a stable average rate','Poisson models counts of independent events in a fixed interval at a constant mean rate.',{tags:['Poisson distribution','conditions']}),
  num('If X~Po(4.5), find E(X).',4.5,'For a Poisson variable, the mean is λ=4.5.',{tags:['Poisson mean']}),
  multi('For X~Po(λ), select all true statements.',['E(X)=λ.','Var(X)=λ.','X can take non-negative integer values.','The maximum possible value is λ.'],['E(X)=λ.','Var(X)=λ.','X can take non-negative integer values.'],'Poisson counts are unbounded non-negative integers, with mean and variance λ.',{questionStyle:'conceptual',tags:['Poisson distribution','properties']})],
'AHL 4.18':[
  mc('Rejecting a true null hypothesis is which error?',['Type I error','Type II error','Sampling frame error','Regression error'],'Type I error','A Type I error is a false positive: rejecting H₀ when it is true.',{tags:['hypothesis testing','Type I error']}),
  mc('A paired t-test is most appropriate for which data?',['Before-and-after scores for the same students','Scores from two unrelated schools','Counts in categories','Two independent proportions'],'Before-and-after scores for the same students','Each before score is naturally paired with the same student’s after score.',{tags:['t-test','paired data']}),
  multi('Select all true statements about statistical power.',['Higher power means a lower chance of Type II error.','Larger samples often increase power.','A very small effect can be harder to detect.','Power is the probability that H₀ is true.'],['Higher power means a lower chance of Type II error.','Larger samples often increase power.','A very small effect can be harder to detect.'],'Power is the probability of rejecting a false null hypothesis.',{questionStyle:'conceptual',tags:['power','Type II error']})],
'AHL 4.19':[
  mc('A column-stochastic transition matrix is applied to a state vector. What should the entries of the new state vector sum to?',['0','1','The number of states','The largest transition probability'],'1','Transition probabilities preserve total probability.',{tags:['Markov chains','state vectors']}),
  num('A two-state system has transition matrix [[0.8,0.3],[0.2,0.7]] acting on column state (0.6,0.4). Find the first component of the next state.',0.6,'The first component is 0.8(0.6)+0.3(0.4)=0.60.',{calculator:'allowed',tags:['transition matrices','state vectors']},0.001),
  multi('Select all true statements about a steady-state vector v.',['Pv=v.','Its entries are probabilities that sum to 1.','Applying the transition again leaves it unchanged.','It must have all entries equal.'],['Pv=v.','Its entries are probabilities that sum to 1.','Applying the transition again leaves it unchanged.'],'A steady state is invariant under the transition but need not be uniform.',{questionStyle:'conceptual',tags:['Markov chains','steady state']})],
}
