import { useState, type FormEvent } from 'react'
import { ArrowRight, BarChart3, CalendarClock, Copy, Plus, Search, UserPlus, Users, X } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, PageHeader, StatusPill } from '../components/UI'
import { courses, getCourse } from '../data/courses'
import { checkPlanGate } from '../lib/plans'
import { useApp } from '../state/AppContext'

export function ClassesPage(){const {state,actions}=useApp();const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [copied,setCopied]=useState('');const gate=checkPlanGate(state,'classes');const classes=state.classes.filter(c=>!c.archived&&c.name.toLowerCase().includes(search.toLowerCase()));return <><PageHeader eyebrow="People & cohorts" title="Classes" description="Keep rosters, assigned practice and course-specific syllabus evidence together." actions={<button className="button primary" disabled={!gate.allowed} onClick={()=>setOpen(true)}><Plus/>Create class</button>}/>{!gate.allowed&&<div className="alert warning">{gate.message} <Link to="/billing">View plans</Link></div>}<div className="class-tools"><label className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search classes…"/></label><span>{classes.length} active classes</span></div><section className="class-grid">{classes.map(item=>{const classAttempts=state.attempts.filter(a=>a.classId===item.id);const answers=classAttempts.flatMap(a=>a.answers);const accuracy=answers.length?Math.round(answers.filter(a=>a.isCorrect).length/answers.length*100):0;const course=getCourse(item.courseId);return <article className="class-card" key={item.id}><header><span className="class-monogram">{course.shortName.split(' ')[0]}</span><StatusPill tone="success">Active</StatusPill></header><h2>{item.name}</h2><p>{course.displayName}</p><div className="class-metrics"><span><Users/><b>{item.members.length}</b><small>students</small></span><span><BarChart3/><b>{accuracy||'—'}{accuracy?'%':''}</b><small>accuracy</small></span><span><CalendarClock/><b>{classAttempts.length}</b><small>attempts</small></span></div><div className="class-code"><span>Join code <b>{item.joinCode}</b></span><button onClick={async()=>{await navigator.clipboard.writeText(item.joinCode);setCopied(item.id);setTimeout(()=>setCopied(''),1200)}}><Copy/>{copied===item.id?'Copied':'Copy'}</button></div><Link to={`/teacher/classes/${item.id}`}>Open class <ArrowRight/></Link></article>})}{classes.length===0&&<EmptyState title="No matching classes" body="Create a class, then share its code with students."/>}</section>{open&&<NewClass initialCourseId={state.activeCourseId} onClose={()=>setOpen(false)} onCreate={(name,courseId)=>{actions.createClass(name,courseId);setOpen(false)}}/>}</>}

function NewClass({initialCourseId,onClose,onCreate}:{initialCourseId:string;onClose:()=>void;onCreate:(name:string,courseId:string)=>void}){const [name,setName]=useState('');const [courseId,setCourseId]=useState(initialCourseId);const submit=(e:FormEvent)=>{e.preventDefault();onCreate(name,courseId)};return <div className="modal-scrim"><form className="small-modal" onSubmit={submit}><header><div><span className="eyebrow">New cohort</span><h2>Create a class</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></header><label>Class name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Grade 11 AI SL"/></label><label>Course<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(course=><option value={course.id} key={course.id}>{course.displayName}</option>)}</select></label><footer><button type="button" className="button tertiary" onClick={onClose}>Cancel</button><button className="button primary">Create class</button></footer></form></div>}

export function ClassDetailPage(){const {id}=useParams();const {state}=useApp();const item=state.classes.find(c=>c.id===id);if(!item)return <EmptyState title="Class not found" body="This class may have been archived."/>;const course=getCourse(item.courseId);const quizzes=state.quizzes.filter(q=>q.mode==='assignment'&&q.courseId===item.courseId);return <><PageHeader eyebrow={`Classes / ${course.shortName}`} title={item.name} description={`${item.members.length} students · ${course.displayName}`} actions={<><Link className="button secondary" to={`/reports/class/${item.id}`}><BarChart3/>View report</Link><Link className="button primary" to="/teacher/quizzes/new"><Plus/>Assign quiz</Link></>}/><div className="class-detail-grid"><section className="panel roster-panel"><div className="panel-head"><div><span className="eyebrow">Roster</span><h2>Students</h2></div><button className="button tertiary small"><UserPlus/>Invite</button></div><div className="roster-table"><div><span>Student</span><span>Recent accuracy</span><span>Attempts</span><span>Last active</span></div>{item.members.map(member=>{const ats=state.attempts.filter(a=>a.studentId===member.id&&(!a.classId||a.classId===item.id));const ans=ats.flatMap(a=>a.answers);const acc=ans.length?Math.round(ans.filter(a=>a.isCorrect).length/ans.length*100):0;return <Link to={`/reports/student/${member.id}`} key={member.id}><span><i>{member.displayName.split(' ').map(n=>n[0]).join('')}</i><b>{member.displayName}</b></span><span><em className={acc<65?'low':''}>{acc||'—'}{acc?'%':''}</em></span><span>{ats.length}</span><span>{ats[0]?new Date(ats[0].startedAt).toLocaleDateString():'Not yet'}</span></Link>})}</div></section><aside><section className="panel join-code-card"><span className="eyebrow">{course.shortName} student join code</span><strong>{item.joinCode}</strong><p>Students enter this once to join the class.</p><button className="button secondary wide" onClick={()=>navigator.clipboard.writeText(item.joinCode)}><Copy/>Copy code</button></section><section className="panel assignment-mini"><div className="panel-head"><div><span className="eyebrow">Practice</span><h2>Assignments</h2></div></div>{quizzes.slice(0,2).map(q=><Link to={`/teacher/quizzes/${q.id}`} key={q.id}><span><b>{q.title}</b><small>{q.questionIds.length} questions</small></span><ArrowRight/></Link>)}</section></aside></div></>}
