import { ArrowRight, BookOpen, CirclePlus, FileJson, RadioTower, Sparkles, TrendingUp, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader, StatCard, percent } from '../components/UI'
import { getCourse } from '../data/courses'
import { syllabusForCourse, topicColors } from '../data/syllabus'
import { questionsForCourse } from '../lib/courseQuestionBank'
import { useApp } from '../state/AppContext'

export function DashboardPage() {
  const {state}=useApp(); const course=getCourse(state.activeCourseId);const syllabusPoints=syllabusForCourse(state.activeCourseId);const courseQuestions=questionsForCourse(state.questions,state.activeCourseId);const questionIds=new Set(courseQuestions.map(question=>question.id));const activeClasses=state.classes.filter(c=>!c.archived&&c.courseId===state.activeCourseId); const answers=state.attempts.flatMap(a=>a.answers).filter(answer=>questionIds.has(answer.questionId));const accuracy=answers.length?answers.filter(a=>a.isCorrect).length/answers.length:0;const today=new Intl.DateTimeFormat(undefined,{weekday:'long',day:'numeric',month:'long'}).format(new Date())
  const pointStats=syllabusPoints.map(point=>{const pointQuestionIds=new Set(courseQuestions.filter(q=>q.syllabusPointId===point.id).map(q=>q.id));const rows=answers.filter(a=>pointQuestionIds.has(a.questionId));return {point,total:rows.length,accuracy:rows.length?rows.filter(a=>a.isCorrect).length/rows.length:1}}).filter(x=>x.total).sort((a,b)=>a.accuracy-b.accuracy)
  const topicCoverage=[1,2,3,4,5].map(topic=>{const points=syllabusPoints.filter(point=>point.topicNumber===topic);const mapped=new Set(courseQuestions.filter(question=>points.some(point=>point.id===question.syllabusPointId)).map(question=>question.syllabusPointId)).size;return {topic,name:points[0]?.topicName??'',mapped,total:points.length,value:points.length?mapped/points.length:0}})
  const recentQuizzes=state.quizzes.filter(quiz=>quiz.courseId===state.activeCourseId)
  const reportClass=activeClasses[0]
  return <>
    <section className="teacher-welcome"><div><span className="eyebrow">{today} · {course.shortName}</span><h1>Good to see you, {state.user?.displayName.split(' ')[0]}.</h1><p>Your clearest classroom signals, mapped to {course.displayName}.</p><div><Link className="button primary" to="/teacher/quizzes/new"><CirclePlus/>Create quiz</Link><Link className="button secondary" to="/teacher/questions/import"><FileJson/>Import questions</Link></div></div><img src={`${import.meta.env.BASE_URL}assets/classroom-maths-hero.png`} alt="Teacher and students exploring graphs and mathematics together"/></section>
    <PageHeader title={`${course.shortName} teaching overview`} description="Plan the next useful move without mixing evidence from another course."/>
    <section className="stats-grid"><StatCard label="Active classes" value={activeClasses.length} detail={`${activeClasses.reduce((n,c)=>n+c.members.length,0)} students enrolled`} tone="green"/><StatCard label="Questions banked" value={courseQuestions.filter(q=>q.status!=='archived').length} detail={`${courseQuestions.filter(q=>q.status==='draft').length} drafts need review`} tone="blue"/><StatCard label="Recent accuracy" value={percent(accuracy)} detail="Across this course" tone="gold"/><StatCard label="Syllabus points covered" value={new Set(courseQuestions.map(q=>q.syllabusPointId)).size} detail={`of ${syllabusPoints.length} mapped points`} tone="purple"/></section>
    <div className="dashboard-grid designed-dashboard">
      <section className="panel syllabus-coverage"><div className="panel-head"><div><span className="eyebrow">Bank health</span><h2>Syllabus coverage</h2></div><Link to="/teacher/questions">Open question bank <ArrowRight/></Link></div><div className="coverage-bars">{topicCoverage.map(item=><div key={item.topic} style={{'--topic-color':topicColors[item.topic]} as React.CSSProperties}><b>{item.topic}</b><span>{item.name}<small>{item.mapped} of {item.total} points</small></span><i><em style={{width:percent(item.value)}}/></i><strong>{percent(item.value)}</strong></div>)}</div></section>
      <aside className="panel import-pulse"><div className="panel-head"><div><span className="eyebrow">Creation pipeline</span><h2>Recent imports</h2></div><Link to="/teacher/questions/import"><FileJson/>New</Link></div>{state.importBatches.length?state.importBatches.slice(0,3).map(batch=><div className="import-pulse-row" key={batch.id}><span><FileJson/></span><div><b>{batch.importedCount} drafts imported</b><small>{new Date(batch.createdAt).toLocaleDateString()} · {batch.errorCount?`${batch.errorCount} needs attention`:'Clean validation'}</small></div><strong>{batch.status.replace('_',' ')}</strong></div>):<div className="dashboard-empty"><FileJson/><b>No imports yet</b><p>Use the prompt studio, then validate a v1.1 question set.</p><Link to="/teacher/questions/prompt-generator">Build a prompt <ArrowRight/></Link></div>}</aside>
      <section className="panel class-pulse"><div className="panel-head"><div><span className="eyebrow">Your classrooms</span><h2>Class pulse</h2></div><Link to="/teacher/classes">Manage classes <ArrowRight/></Link></div><div className="class-summary-grid">{activeClasses.map((classroom,index)=><Link to={`/teacher/classes/${classroom.id}`} key={classroom.id}><span className={`class-topic topic-${(index%5)+1}`}>{classroom.name.split(' ').slice(0,2).map(word=>word[0]).join('')}</span><div><b>{classroom.name}</b><small><Users/>{classroom.members.length} students · code {classroom.joinCode}</small></div><strong>{index===0?'72%':'78%'}<small>accuracy</small></strong><ArrowRight/></Link>)}</div></section>
      <aside className="panel quick-panel refined"><div className="panel-head"><div><span className="eyebrow">Start something</span><h2>Quick actions</h2></div></div><Link to="/teacher/quizzes/new"><span className="quick-icon blue"><RadioTower/></span><div><b>Run a live check</b><small>Leaderboard, streaks and powerups</small></div><ArrowRight/></Link><Link to="/teacher/questions/prompt-generator"><span className="quick-icon green"><Sparkles/></span><div><b>Generate a prompt</b><small>Grounded in a real syllabus point</small></div><ArrowRight/></Link>{reportClass&&<Link to={`/reports/class/${reportClass.id}`}><span className="quick-icon orange"><TrendingUp/></span><div><b>Review weak points</b><small>Turn attempts into lesson priorities</small></div><ArrowRight/></Link>}</aside>
      <section className="panel dashboard-main"><div className="panel-head"><div><span className="eyebrow">Syllabus signal</span><h2>Points to revisit</h2></div>{reportClass&&<Link to={`/reports/class/${reportClass.id}`}>Open full report <ArrowRight/></Link>}</div><div className="mastery-list">{pointStats.slice(0,5).map(({point,accuracy,total})=><div key={point.id}><span className="topic-dot" style={{background:`var(--topic-${point.topicNumber})`}}/><div className="mastery-label"><b>{point.code}</b><span>{point.title}</span></div><div className="mastery-track"><i><b className={accuracy<.65?'low':''} style={{width:percent(accuracy)}}/></i><small>{total} responses</small></div><strong>{percent(accuracy)}</strong></div>)}</div></section>
      <aside className="panel recent-panel"><div className="panel-head"><div><span className="eyebrow">Ready to reuse</span><h2>Recent quizzes</h2></div><Link to="/teacher/quizzes/new">New quiz</Link></div><div className="recent-list">{recentQuizzes.slice(0,3).map(quiz=><Link to={`/teacher/quizzes/${quiz.id}`} key={quiz.id}><span className={`quiz-kind ${quiz.mode}`}>{quiz.mode==='live'?<RadioTower/>:<BookOpen/>}</span><div><b>{quiz.title}</b><small>{quiz.questionIds.length} questions · {quiz.mode}</small></div><span>{new Date(quiz.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><ArrowRight/></Link>)}</div></aside>
    </div>
  </>
}
