import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Award, Check, CircleStop, Copy, Crown, Flame, Maximize, Pause, Play, RadioTower, Trophy, Users, Zap } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, SyllabusChip, titleCase } from '../components/UI'
import { getCourse } from '../data/courses'
import { syllabusById } from '../data/syllabus'
import { useApp } from '../state/AppContext'
import { isSupabaseConfigured } from '../lib/supabase'
import { subscribeToLiveSession } from '../lib/cloudRepository'
import { liveJoinUrl, playUrl } from '../lib/joinUrl'
import { isLiveQuestionRevealed, liveCorrectAnswerLabel, liveQuestionPhase } from '../lib/liveGameRepository'
import { QRCodeSVG } from 'qrcode.react'
import type { Question } from '../types'

export function LiveControlPage(){
  const {sessionId}=useParams();const {state,actions}=useApp();const session=state.sessions.find(s=>s.id===sessionId);const quiz=state.quizzes.find(q=>q.id===session?.quizId);const limit=quiz?.settings.timeLimitSeconds??30;const [seconds,setSeconds]=useState(limit);const [copied,setCopied]=useState<'url'|'pin'|''>('');const [controlError,setControlError]=useState('');const questions=useMemo(()=>quiz?.questionIds.map(id=>state.questions.find(q=>q.id===id)).filter(Boolean) as Question[]??[],[quiz,state.questions]);const question=questions[session?.currentQuestionIndex??-1];const phase=liveQuestionPhase(session);const revealed=isLiveQuestionRevealed(session)
  useEffect(()=>{if(session?.status!=='live'||revealed)return;const timer=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(timer)},[session?.status,session?.currentQuestionIndex,revealed])
  useEffect(()=>{setSeconds(limit)},[session?.currentQuestionIndex,limit])
  useEffect(()=>{if(!sessionId||!isSupabaseConfigured)return;return subscribeToLiveSession(sessionId,()=>{void actions.refreshCloud()})},[sessionId,actions])
  if(!session||!quiz)return <EmptyState title="Session not found" body="Start a new session from a saved quiz."/>
  const responses=question?session.participants.filter(p=>p.answers[question.id]).length:0
  const leaderboard=[...session.participants].sort((a,b)=>b.score-a.score)
  const runControl=async(task:()=>Promise<void>)=>{setControlError('');try{await task()}catch{setControlError('Could not update the live game. Check your connection.')}}
  const start=()=>runControl(()=>actions.updateSession(session.id,{status:'live',currentQuestionIndex:0,revealedQuestionIndex:-1,questionStartedAt:new Date().toISOString(),startedAt:new Date().toISOString()}))
  const reveal=()=>question?runControl(()=>actions.revealQuestion(session.id,question.id)):Promise.resolve()
  const next=()=>runControl(()=>session.currentQuestionIndex>=questions.length-1?actions.updateSession(session.id,{status:'ended',endedAt:new Date().toISOString()}):actions.updateSession(session.id,{status:'live',currentQuestionIndex:session.currentQuestionIndex+1,revealedQuestionIndex:-1,questionStartedAt:new Date().toISOString()}))
  const copyValue=async(kind:'url'|'pin',value:string)=>{await navigator.clipboard.writeText(value);setCopied(kind);window.setTimeout(()=>setCopied(''),1500)}
  const openFullscreen=()=>{if(!document.fullscreenElement)void document.documentElement.requestFullscreen();else void document.exitFullscreen()}
  if(session.status==='waiting'){
    const joinUrl=liveJoinUrl(session.pin);const basePlayUrl=playUrl();const course=getCourse(quiz.courseId);const topics=[...new Set(questions.map(question=>syllabusById.get(question.syllabusPointId)?.topicName).filter(Boolean))]
    return <div className="live-stage lobby-stage"><div className="live-math-texture"/><header><Link to={`/teacher/quizzes/${quiz.id}`}>MathPulse</Link><div><span><Users/>{session.participants.length} joined</span><button onClick={openFullscreen}><Maximize/>Fullscreen</button></div></header><main className="projector-lobby"><div className="lobby-heading"><div className="live-eyebrow"><RadioTower/>{course.shortName} live lobby</div><h1>{quiz.title}</h1><p>{topics.slice(0,2).join(' · ')||course.displayName}</p><p>Join with the QR code, the URL, or enter the PIN at <b>{basePlayUrl}</b>.</p>{controlError&&<div className="alert danger">{controlError}</div>}</div><div className="join-board"><section className="qr-panel"><div className="qr-frame"><QRCodeSVG value={joinUrl} size={224} level="M" bgColor="#ffffff" fgColor="#143f39" marginSize={1} title={`Join ${quiz.title}`}/></div><span>Scan to join this quiz</span></section><section className="lobby-access"><div className="game-pin"><span>GAME PIN</span><strong>{session.pin}</strong><button onClick={()=>copyValue('pin',session.pin)}><Copy/>{copied==='pin'?'PIN copied':'Copy PIN'}</button></div><div className="join-url-card"><span>STUDENT JOIN URL</span><strong>{joinUrl}</strong><button onClick={()=>copyValue('url',joinUrl)}><Copy/>{copied==='url'?'URL copied':'Copy URL'}</button></div></section></div><div className="lobby-bottom"><div className="participant-cloud">{session.participants.map((p,i)=><span key={p.id} style={{'--delay':`${i*80}ms`} as React.CSSProperties}>{p.nickname}</span>)}{!session.participants.length&&<em>Waiting for your first player…</em>}</div><button className="start-live" onClick={()=>void start()} disabled={!session.participants.length}><Play/>Start quiz</button></div><div className="lobby-settings"><span>{limit}s per question</span><span>{quiz.settings.enablePowerups?<><Zap/>Powerups on</>:'Powerups off'}</span><span>{quiz.settings.enableStreakBonuses?<><Flame/>Streaks on</>:'Streaks off'}</span></div></main><footer><span>{course.shortName} · {quiz.title}</span><span>{questions.length} questions</span></footer></div>
  }
  if(session.status==='ended')return <div className="live-stage leaderboard-stage"><div className="live-math-texture"/><header><b>MathPulse</b><span>Final standings</span></header><main><div className="live-eyebrow"><Crown/>Session complete</div><h1>Brilliant work.</h1><div className="podium-list">{leaderboard.map((p,i)=><div key={p.id} className={`place-${i+1}`}><b>{i+1}</b><span>{p.nickname}<small>{p.badges.length>0&&<><Award/>{p.badges.length} badge{p.badges.length===1?'':'s'}</>}</small></span><strong>{p.score.toLocaleString()}</strong></div>)}</div><Link className="button light" to={`/reports/class/${session.classId??state.classes[0]?.id}`}>Open syllabus report <ArrowRight/></Link></main></div>
  if(!question)return null
  const answerCounts=question.options?.map(o=>({...o,count:session.participants.filter(p=>{const answer=p.answers[question.id]?.answer;return Array.isArray(answer)?answer.includes(o.text):String(answer)===o.text}).length}))??[]
  return <div className={`live-stage question-stage ${phase}-phase`}><div className="live-math-texture"/><header><b>MathPulse</b><div><span>Question {session.currentQuestionIndex+1} / {questions.length}</span><button onClick={()=>void runControl(()=>actions.updateSession(session.id,{status:session.status==='paused'?'live':'paused'}))}>{session.status==='paused'?<Play/>:<Pause/>}</button><button onClick={openFullscreen}><Maximize/></button></div></header><main>{controlError&&<div className="alert danger">{controlError}</div>}<div className="live-question-meta"><SyllabusChip id={question.syllabusPointId}/><span>{titleCase(question.type)}</span><em>{revealed?'Answer revealed':'Answering'}</em><span className={`timer ${seconds<8?'urgent':''}`}>{seconds}</span></div><h1>{question.prompt}</h1>{answerCounts.length>0?<div className={`live-answer-grid ${answerCounts.length===2?'two-options':''}`}>{answerCounts.map((o,i)=><div className={revealed?(o.isCorrect?'answer-correct':'answer-incorrect'):'answer-choice'} key={o.id}><b>{['◆','▲','●','■'][i]}</b><span>{o.text}</span>{revealed&&<div className="choice-result"><em>{o.isCorrect?'Correct':'Incorrect'}</em><strong>{o.count}</strong></div>}</div>)}</div>:<div className={`live-written ${revealed?'answer-correct':''}`}><span>{revealed?'Expected answer':'Interactive response'}</span><strong>{revealed?liveCorrectAnswerLabel(question):'Students are working on their devices…'}</strong></div>}{revealed&&<div className="reveal-layout"><section className="explanation-reveal" aria-live="polite"><Check/><div><h2>Explanation</h2><p>{question.explanation}</p></div></section>{quiz.settings.showLeaderboard&&<aside className="round-leaderboard"><span><Trophy/>Leaderboard</span>{leaderboard.slice(0,5).map((player,index)=><div key={player.id}><b>{index+1}</b><span>{player.nickname}</span><strong>{player.score.toLocaleString()}</strong></div>)}</aside>}</div>}</main><footer><div><Users/><b>{responses}</b><span>of {session.participants.length} answered</span></div><i><b style={{width:`${session.participants.length?responses/session.participants.length*100:0}%`}}/></i>{!revealed?<button className="button light" onClick={()=>void reveal()}>Reveal Answer</button>:<button className="button light" onClick={()=>void next()}>{session.currentQuestionIndex===questions.length-1?<><CircleStop/>Finish</>:<>Next question<ArrowRight/></>}</button>}</footer></div>
}
