import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ArrowRight, Award, BadgeCheck, CheckCircle2, Flame, LoaderCircle, RadioTower, Shield, Snowflake, Sparkles, Split, Trophy, XCircle, Zap } from 'lucide-react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Logo } from '../components/Logo'
import { emptyAnswerFor, isAnswerReady, QuestionAnswerInput } from '../components/QuestionAnswerInput'
import { titleCase } from '../components/UI'
import { useApp } from '../state/AppContext'
import type { BadgeType, PowerupType } from '../types'

const powerupDetails:Record<PowerupType,{label:string;short:string;icon:typeof Zap}>={
  double_points:{label:'Double Points',short:'2× score',icon:Zap},
  fifty_fifty:{label:'Fifty-Fifty',short:'Hide 2',icon:Split},
  time_freeze:{label:'Time Freeze',short:'+8 sec',icon:Snowflake},
  shield:{label:'Shield',short:'Save streak',icon:Shield},
}
const badgeLabels:Record<BadgeType,string>={fastest_correct:'Fastest Correct',hot_streak:'Hot Streak',comeback:'Comeback',topic_master:'Topic Master',perfect_round:'Perfect Round'}

export function PlayPage(){const [params]=useSearchParams();const {state}=useApp();const initialPin=(params.get('pin')??'').replace(/\D/g,'').slice(0,6);const [pin,setPin]=useState(initialPin);const navigate=useNavigate();const session=state.sessions.find(item=>item.pin===pin&&item.status!=='ended');const quiz=state.quizzes.find(item=>item.id===session?.quizId);const submit=(e:FormEvent)=>{e.preventDefault();navigate(`/play/${pin.trim()}`)};return <div className="play-page join-page"><div className="play-texture"/><header><Logo/></header><main><span className="play-kicker">Live IB Mathematics</span><span className="play-icon"><RadioTower/></span><h1>{quiz?`Join ${quiz.title}`:'Ready to make your move?'}</h1><p>{quiz?'This live room is open. Confirm the PIN and continue.':'Enter the six-digit PIN from your classroom screen.'}</p><form onSubmit={submit}><label>Game PIN<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="000 000" aria-label="Game PIN" autoFocus/></label><button className="button coral wide" disabled={pin.length!==6}>Enter arena <ArrowRight/></button></form>{session&&<span className="session-found"><RadioTower/>Live now · {session.participants.length} joined</span>}<span className="join-help">Joining a class instead? <Link to="/login">Sign in first</Link></span></main></div>}

export function PlaySessionPage(){
  const {pin}=useParams();const {state,actions}=useApp();const [nickname,setNickname]=useState('');const [participantId,setParticipantId]=useState(()=>sessionStorage.getItem(`mathpulse-player-${pin}`)||'');const [error,setError]=useState('');const [answer,setAnswer]=useState<unknown>('');const [startTime,setStartTime]=useState(Date.now());const [seconds,setSeconds]=useState(30);const [powerupNotice,setPowerupNotice]=useState('')
  const session=state.sessions.find(s=>s.pin===pin);const quiz=state.quizzes.find(q=>q.id===session?.quizId);const participant=session?.participants.find(p=>p.id===participantId);const questionId=quiz?.questionIds[session?.currentQuestionIndex??-1];const question=state.questions.find(q=>q.id===questionId);const submitted=question&&participant?.answers[question.id];const revealed=session?.revealedQuestionIndex===session?.currentQuestionIndex
  const leaderboard=useMemo(()=>[...(session?.participants??[])].sort((a,b)=>b.score-a.score),[session?.participants]);const rank=leaderboard.findIndex(item=>item.id===participantId)+1
  useEffect(()=>{if(!question)return;setAnswer(emptyAnswerFor(question));setStartTime(Date.now());setSeconds(quiz?.settings.timeLimitSeconds??30);setPowerupNotice('')},[session?.currentQuestionIndex,question?.id,quiz?.settings.timeLimitSeconds])
  useEffect(()=>{if(session?.status!=='live'||submitted||revealed)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer)},[session?.status,submitted,revealed,question?.id])
  const join=(e:FormEvent)=>{e.preventDefault();try{const result=actions.joinSession(pin??'',nickname.trim());setParticipantId(result.participantId);sessionStorage.setItem(`mathpulse-player-${pin}`,result.participantId)}catch(err){setError(err instanceof Error?err.message:'Unable to join')}}
  const submit=()=>{if(!session||!participantId||!question||!isAnswerReady(question,answer))return;actions.submitLiveAnswer(session.id,participantId,question.id,answer,Date.now()-startTime)}
  const usePowerup=(type:PowerupType)=>{if(!session||!participant||!question)return;if(actions.usePowerup(session.id,participant.id,question.id,type))setPowerupNotice(`${powerupDetails[type].label} armed`)}
  const hiddenOptions=useMemo(()=>{const hidden=new Set<string>();const activePowerup=participant?.activePowerup;if(!activePowerup||!question||activePowerup.questionId!==question.id||activePowerup.type!=='fifty_fifty')return hidden;question.options?.filter(option=>!option.isCorrect).slice(0,2).forEach(option=>hidden.add(option.id));return hidden},[participant?.activePowerup,question])

  if(!session)return <div className="play-page join-page"><header><Logo/></header><main><span className="play-icon error">?</span><h1>Game not found</h1><p>Check the PIN on the main screen and try again.</p><Link className="button primary" to="/play">Try another PIN</Link></main></div>
  if(!participantId||!participant)return <div className="play-page join-page nickname-page"><div className="play-texture"/><header><Logo/></header><main><span className="play-kicker">PIN {session.pin}</span><span className="play-icon"><Sparkles/></span><h1>Join {quiz?.title}</h1><p>Choose the name your teacher will recognize.</p>{error&&<div className="alert danger">{error}</div>}<form onSubmit={join}><label>Nickname<input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={28} placeholder="Your nickname" autoFocus required/></label><button className="button coral wide">Join game <ArrowRight/></button></form></main></div>
  if(session.status==='waiting'||session.status==='paused')return <div className="play-page waiting-page"><div className="play-texture"/><header><Logo/><span className="score-chip">{participant.score.toLocaleString()} pts</span></header><main><div className="waiting-orbit"><LoaderCircle className="spin"/><i/><i/><i/></div><span className="play-kicker">You’re on the roster</span><h1>Nice one, {participant.nickname}.</h1><p>{session.status==='paused'?'Quick pause. Your streak and score are safe.':'Look up—the first question will appear when your teacher starts.'}</p><div className="lobby-roster">{session.participants.slice(0,8).map(player=><span key={player.id}>{player.nickname.slice(0,1)}</span>)}</div><strong>{session.participants.length} player{session.participants.length===1?'':'s'} ready</strong><small>PIN {session.pin}</small></main></div>
  if(session.status==='ended')return <div className="play-page finish-page"><div className="play-texture"/><header><Logo/></header><main><Trophy/><span className="play-kicker">Final result · #{rank}</span><h1>{participant.score.toLocaleString()}</h1><p>Every response has been added to your syllabus progress.</p><div className="mini-leaderboard">{leaderboard.slice(0,3).map((player,index)=><div className={player.id===participant.id?'you':''} key={player.id}><b>{index+1}</b><span>{player.nickname}</span><strong>{player.score.toLocaleString()}</strong></div>)}</div>{participant.badges.length>0&&<div className="badge-rack"><span>Your badges</span><div>{participant.badges.map(badge=><b key={badge.type}><BadgeCheck/>{badgeLabels[badge.type]}</b>)}</div></div>}<Link className="button light" to="/play">Join another game</Link></main></div>
  if(!question)return null
  if(submitted)return <div className={`play-page feedback-page ${revealed?(submitted.correct?'correct':'incorrect'):'locked'}`}><div className="play-texture"/><header><Logo/><span className="score-chip">{participant.score.toLocaleString()} pts</span></header><main>{!revealed?<><LoaderCircle className="spin"/><span className="play-kicker">Answer locked</span><h1>Eyes on the main screen…</h1><p>Your result appears when your teacher reveals the answer.</p></>:<>{submitted.correct?<CheckCircle2/>:<XCircle/>}<span className="play-kicker">{submitted.correct?'That’s right':'Not this time'}</span><h1>{submitted.correct?`+${submitted.awardedPoints.toLocaleString()} points`:'Keep moving'}</h1><div className="score-breakdown"><span>Base <b>{submitted.scoreDetail.basePoints}</b></span><span>Speed <b>+{submitted.scoreDetail.speedBonus}</b></span><span>Streak <b>+{submitted.scoreDetail.streakBonus}</b></span>{submitted.scoreDetail.multiplier>1&&<span>Powerup <b>×{submitted.scoreDetail.multiplier}</b></span>}{submitted.scoreDetail.shieldUsed&&<span>Shield <b>Streak saved</b></span>}</div>{quiz?.settings.showExplanations&&<div className="phone-explanation"><b>Why?</b><p>{question.explanation}</p></div>}<div className="feedback-footer"><span><Flame/>{participant.currentStreak} streak</span><span><Trophy/>#{rank} place</span></div></>}</main></div>
  return <div className="play-page answer-page"><div className="play-texture"/><header><Logo/><div><span><Flame/>{participant.currentStreak}</span><span>{participant.score.toLocaleString()} pts</span></div></header><div className="phone-progress"><i style={{width:`${((session.currentQuestionIndex+1)/(quiz?.questionIds.length??1))*100}%`}}/></div><main><div className="answer-meta"><small>{titleCase(question.type)}</small><span className={seconds<8?'urgent':''}>{seconds}s</span></div><h1>{question.prompt}</h1>{quiz?.settings.enablePowerups&&<div className="powerup-tray"><span>Powerups</span><div>{(Object.keys(powerupDetails) as PowerupType[]).map(type=>{const detail=powerupDetails[type];const Icon=detail.icon;const count=participant.powerups[type]??0;const active=participant.activePowerup?.questionId===question.id&&participant.activePowerup.type===type;return <button type="button" className={active?'active':''} disabled={!count||Boolean(participant.activePowerup?.questionId===question.id)} onClick={()=>usePowerup(type)} key={type} title={detail.label}><Icon/><b>{detail.short}</b><em>{count}</em></button>})}</div>{powerupNotice&&<small>{powerupNotice}</small>}</div>}<QuestionAnswerInput question={question} value={answer} onChange={setAnswer} hiddenOptions={hiddenOptions}/><button className="button coral wide submit-answer" onClick={submit} disabled={!isAnswerReady(question,answer)}>Lock answer</button></main></div>
}
