import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Archive, Check, ChevronDown, Copy, FileJson, Filter, MoreHorizontal, Plus, Search, Send, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState, PageHeader, SyllabusChip, StatusPill, titleCase } from '../components/UI'
import { courses } from '../data/courses'
import { syllabusById, syllabusForCourse } from '../data/syllabus'
import { filterQuestionBank } from '../lib/courseQuestionBank'
import { checkPlanGate } from '../lib/plans'
import { useApp } from '../state/AppContext'
import type { CalculatorMode, Difficulty, Question, QuestionOption, QuestionStyle, QuestionType } from '../types'

const questionTypes:QuestionType[]=['multiple_choice','numeric_answer','short_answer','multi_select','true_false','matching','ordering','drag_drop','fill_blank']

export function QuestionsPage() {
  const {state,actions}=useApp(); const [tab,setTab]=useState<'mine'|'public'|'drafts'>('mine'); const [search,setSearch]=useState(''); const [courseId,setCourseId]=useState(state.activeCourseId); const [topic,setTopic]=useState('all'); const [pointId,setPointId]=useState('all'); const [type,setType]=useState('all');const [difficulty,setDifficulty]=useState('all');const [calculator,setCalculator]=useState('all'); const [editing,setEditing]=useState<Question|null>(null); const [showNew,setShowNew]=useState(false); const [openMenu,setOpenMenu]=useState('')
  const coursePoints=useMemo(()=>syllabusForCourse(courseId),[courseId])
  useEffect(()=>{if(state.activeCourseId!==courseId){setCourseId(state.activeCourseId);setTopic('all');setPointId('all')}},[state.activeCourseId,courseId])
  const courseQuestions=useMemo(()=>filterQuestionBank(state.questions,{courseId,topic:topic==='all'?'all':Number(topic),syllabusPointId:pointId,difficulty:difficulty as Difficulty|'all',calculator:calculator as CalculatorMode|'all',type:type as QuestionType|'all',search}),[state.questions,courseId,topic,pointId,difficulty,calculator,type,search])
  const questions=useMemo(()=>courseQuestions.filter(q=>q.status!=='archived').filter(q=>tab==='public'?q.visibility==='public'&&q.status==='approved':tab==='drafts'?q.status==='draft':q.createdBy===state.user?.id||q.createdBy==='teacher-demo'),[courseQuestions,state.user,tab])
  const bankTabCount=(target:'mine'|'public'|'drafts')=>courseQuestions.filter(q=>q.status!=='archived').filter(q=>target==='public'?q.visibility==='public'&&q.status==='approved':target==='drafts'?q.status==='draft':q.createdBy===state.user?.id||q.createdBy==='teacher-demo').length
  const changeCourse=(value:string)=>{setCourseId(value);actions.setActiveCourse(value);setTopic('all');setPointId('all')}
  const gate=checkPlanGate(state,'private_questions')
  return <>
    <PageHeader eyebrow="Question library" title="Question bank" description="Build once, find fast, and keep every question attached to its syllabus purpose." actions={<><Link className="button secondary" to="/teacher/questions/import"><FileJson size={17}/>Import JSON</Link><button className="button primary" onClick={()=>setShowNew(true)} disabled={!gate.allowed}><Plus size={18}/>New question</button></>}/>
    {!gate.allowed&&<div className="alert warning">{gate.message} <Link to="/billing">View plans</Link></div>}
    <section className="panel table-panel"><div className="bank-tabs"><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>My bank <span>{bankTabCount('mine')}</span></button><button className={tab==='public'?'active':''} onClick={()=>setTab('public')}>Shared bank <span>{bankTabCount('public')}</span></button><button className={tab==='drafts'?'active':''} onClick={()=>setTab('drafts')}>Drafts <span>{bankTabCount('drafts')}</span></button></div><div className="table-tools question-bank-tools"><label className="search-box"><Search/><input placeholder="Search prompts, tags, or syllabus points…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="select-wrap course-bank-select"><select value={courseId} onChange={e=>changeCourse(e.target.value)} aria-label="Course">{courses.map(course=><option value={course.id} key={course.id}>{course.displayName}</option>)}</select><ChevronDown/></label><label className="select-wrap"><Filter/><select value={pointId} onChange={e=>setPointId(e.target.value)}><option value="all">All syllabus points</option>{coursePoints.map(point=><option value={point.id} key={point.id}>{point.code} · {point.title}</option>)}</select><ChevronDown/></label><label className="select-wrap"><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All question types</option>{questionTypes.map(value=><option value={value} key={value}>{titleCase(value)}</option>)}</select><ChevronDown/></label><label className="select-wrap"><select value={calculator} onChange={e=>setCalculator(e.target.value)}><option value="all">Any calculator setting</option><option value="allowed">Calculator allowed</option><option value="not_allowed">No calculator</option><option value="neutral">Neutral</option></select><ChevronDown/></label></div><div className="bank-filter-chips"><span>Syllabus</span><button className={topic==='all'?'active':''} onClick={()=>{setTopic('all');setPointId('all')}}>All</button>{[1,2,3,4,5].map(n=><button className={`${topic===String(n)?'active ':''}topic-${n}`} onClick={()=>{setTopic(String(n));setPointId('all')}} key={n}>Topic {n}</button>)}<i/><span>Difficulty</span>{['all','foundation','standard','extension'].map(value=><button className={difficulty===value?'active':''} onClick={()=>setDifficulty(value)} key={value}>{titleCase(value)}</button>)}</div>
      <div className="question-table"><div className="question-row table-header"><span>Question</span><span>Syllabus point</span><span>Type</span><span>Status</span><span/></div>{questions.map(q=><div className="question-row" key={q.id} onClick={()=>setEditing(q)}><div className="question-cell"><span className={`difficulty-dot ${q.difficulty}`}/><div><b>{q.prompt}</b><small>{titleCase(q.questionStyle??'conceptual')} · {titleCase(q.difficulty)} · {q.estimatedTimeSeconds??60}s · {q.marksEstimate??1} mark{(q.marksEstimate??1)===1?'':'s'}</small></div></div><div><SyllabusChip id={q.syllabusPointId}/></div><span>{titleCase(q.type)}</span><span><StatusPill tone={q.status==='approved'?'success':q.status==='pending_review'?'warning':'neutral'}>{titleCase(q.status)}</StatusPill></span><div className="row-menu"><button onClick={e=>{e.stopPropagation();setOpenMenu(openMenu===q.id?'':q.id)}}><MoreHorizontal/></button>{openMenu===q.id&&<div className="menu-pop"><button onClick={e=>{e.stopPropagation();actions.duplicateQuestion(q.id);setOpenMenu('')}}><Copy/>Duplicate</button>{q.status==='draft'&&<button onClick={e=>{e.stopPropagation();actions.submitQuestion(q.id);setOpenMenu('')}}><Send/>Submit to public bank</button>}<button className="danger-text" onClick={e=>{e.stopPropagation();actions.archiveQuestion(q.id);setOpenMenu('')}}><Archive/>Archive</button></div>}</div></div>)}{questions.length===0&&<EmptyState title="No questions here yet" body="Clear a filter, import a JSON set, or create a syllabus-tagged question." action={<button className="button primary" onClick={()=>setShowNew(true)}><Plus/>Create question</button>}/>}</div>
    </section>
    {(showNew||editing)&&<QuestionEditor question={editing} initialCourseId={courseId} onClose={()=>{setShowNew(false);setEditing(null)}} onSave={q=>{editing?actions.updateQuestion(q):actions.addQuestions([q]);setShowNew(false);setEditing(null)}}/>}
  </>
}

function QuestionEditor({question,initialCourseId,onClose,onSave}:{question:Question|null;initialCourseId:string;onClose:()=>void;onSave:(q:Question)=>void}){
  const {state}=useApp(); const [courseId,setCourseId]=useState(question?.courseId??initialCourseId); const editorPoints=syllabusForCourse(courseId); const [pointId,setPointId]=useState(question?.syllabusPointId??editorPoints[0].id); const [type,setType]=useState<QuestionType>(question?.type??'multiple_choice'); const [difficulty,setDifficulty]=useState<Difficulty>(question?.difficulty??'standard');const [questionStyle,setQuestionStyle]=useState<QuestionStyle>(question?.questionStyle??'conceptual');const [calculator,setCalculator]=useState<CalculatorMode>(question?.calculator??'neutral');const [estimatedTime,setEstimatedTime]=useState(question?.estimatedTimeSeconds??60);const [marks,setMarks]=useState(question?.marksEstimate??1); const [prompt,setPrompt]=useState(question?.prompt??''); const [answer,setAnswer]=useState(String(question?.answerData.answer??'')); const [explanation,setExplanation]=useState(question?.explanation??''); const [tags,setTags]=useState(question?.tags.join(', ')??''); const [choices,setChoices]=useState(question?.options?.map(o=>o.text)??['','','','']);const [multiAnswers,setMultiAnswers]=useState<string[]>(question?.options?.filter(o=>o.isCorrect).map(o=>o.text)??(question?.answerData.answers as string[]??[]));const [accepted,setAccepted]=useState((question?.answerData.acceptedAnswers as string[]|undefined)?.join(' | ')??'');const [pairs,setPairs]=useState<Array<{left:string;right:string}>>((question?.answerData.pairs as Array<{left:string;right:string}>|undefined)??[{left:'',right:''},{left:'',right:''},{left:'',right:''}]);const [orderText,setOrderText]=useState(((question?.answerData.correctOrder??question?.answerData.items??[]) as string[]).join('\n'));const [zonesText,setZonesText]=useState(((question?.answerData.zones??[]) as string[]).join(', '));const [dragItems,setDragItems]=useState<Array<{text:string;correctZone:string}>>((question?.answerData.items as Array<{text:string;correctZone:string}>|undefined)??[{text:'',correctZone:''},{text:'',correctZone:''}])
  const updateChoice=(index:number,value:string)=>{const previous=choices[index];const next=[...choices];next[index]=value;if(answer===previous)setAnswer(value);if(multiAnswers.includes(previous))setMultiAnswers(multiAnswers.map(item=>item===previous?value:item));setChoices(next)}
  const buildOptions=():QuestionOption[]|undefined=>{
    const values=type==='true_false'?['True','False']:type==='multiple_choice'||type==='multi_select'?choices:undefined
    return values?.map((text,index)=>({id:question?.options?.[index]?.id??crypto.randomUUID(),label:String.fromCharCode(65+index),text,isCorrect:type==='multi_select'?multiAnswers.includes(text):type==='true_false'?(answer==='true')===(text==='True'):text===answer,sortOrder:index}))
  }
  const buildAnswerData=():Record<string,unknown>=>{
    if(type==='numeric_answer')return {answer:Number(answer),tolerance:0}
    if(type==='short_answer'||type==='fill_blank')return {answer,acceptedAnswers:accepted.split('|').map(value=>value.trim()).filter(Boolean)}
    if(type==='multi_select')return {answers:multiAnswers}
    if(type==='true_false')return {answer:answer==='true'}
    if(type==='matching')return {pairs:pairs.filter(pair=>pair.left.trim()&&pair.right.trim())}
    if(type==='ordering'){const correctOrder=orderText.split('\n').map(value=>value.trim()).filter(Boolean);return {items:[...correctOrder].reverse(),correctOrder}}
    if(type==='drag_drop')return {zones:zonesText.split(',').map(value=>value.trim()).filter(Boolean),items:dragItems.filter(item=>item.text.trim()&&item.correctZone.trim())}
    return {answer}
  }
  const submit=(e:FormEvent)=>{e.preventDefault();const now=new Date().toISOString();onSave({id:question?.id??crypto.randomUUID(),createdBy:question?.createdBy??state.user?.id??'teacher-demo',visibility:question?.visibility??'private',status:question?.status??'draft',courseId:syllabusById.get(pointId)?.courseId??courseId,syllabusPointId:pointId,type,prompt,answerData:buildAnswerData(),explanation,difficulty,questionStyle,calculator,estimatedTimeSeconds:estimatedTime,marksEstimate:marks,tags:tags.split(',').map(t=>t.trim()).filter(Boolean),source:question?.source??'manual',options:buildOptions(),createdAt:question?.createdAt??now,updatedAt:now})}
  const setPair=(index:number,key:'left'|'right',value:string)=>setPairs(pairs.map((pair,i)=>i===index?{...pair,[key]:value}:pair));const setDrag=(index:number,key:'text'|'correctZone',value:string)=>setDragItems(dragItems.map((item,i)=>i===index?{...item,[key]:value}:item))
  return <div className="modal-scrim"><form className="editor-sheet" onSubmit={submit}><div className="sheet-head"><div><span className="eyebrow">{question?'Edit question':'Create question'}</span><h2>{question?'Refine the details':'Add to your private bank'}</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><div className="form-grid"><label>Course<select value={courseId} onChange={e=>{const next=e.target.value;setCourseId(next);setPointId(syllabusForCourse(next)[0].id)}}>{courses.map(course=><option value={course.id} key={course.id}>{course.shortName}</option>)}</select></label><label>Syllabus point<select value={pointId} onChange={e=>setPointId(e.target.value)}>{[1,2,3,4,5].map(n=><optgroup label={`Topic ${n}`} key={n}>{editorPoints.filter(p=>p.topicNumber===n).map(p=><option value={p.id} key={p.id}>{p.code} · {p.title}</option>)}</optgroup>)}</select></label><label>Question type<select value={type} onChange={e=>{setType(e.target.value as QuestionType);setAnswer(e.target.value==='true_false'?'true':'')}}>{questionTypes.map(value=><option value={value} key={value}>{titleCase(value)}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="foundation">Foundation</option><option value="standard">Standard</option><option value="extension">Extension</option></select></label><div className="metadata-grid full"><label>Question style<select value={questionStyle} onChange={e=>setQuestionStyle(e.target.value as QuestionStyle)}>{['recall','procedural','conceptual','misconception','application','exam_style'].map(value=><option value={value} key={value}>{titleCase(value)}</option>)}</select></label><label>Calculator<select value={calculator} onChange={e=>setCalculator(e.target.value as CalculatorMode)}><option value="neutral">Neutral</option><option value="allowed">Allowed</option><option value="not_allowed">Not allowed</option></select></label><label>Estimated time<input type="number" min={10} max={900} value={estimatedTime} onChange={e=>setEstimatedTime(Number(e.target.value))}/></label><label>Marks estimate<input type="number" min={1} max={20} value={marks} onChange={e=>setMarks(Number(e.target.value))}/></label></div><label className="full">Prompt<textarea rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={type==='fill_blank'?'Use ___ to show the blank.':'Write a concise, unambiguous question.'} required/></label>
      {(type==='multiple_choice'||type==='multi_select')&&<div className="choice-editor full"><span>Choices <small>{type==='multi_select'?'Select every correct answer':'Select the correct answer'}</small></span>{choices.map((choice,i)=><label key={i}><input type={type==='multi_select'?'checkbox':'radio'} name="answer" checked={type==='multi_select'?multiAnswers.includes(choice):answer===choice&&choice!==''} onChange={()=>type==='multi_select'?setMultiAnswers(multiAnswers.includes(choice)?multiAnswers.filter(item=>item!==choice):[...multiAnswers,choice]):setAnswer(choice)}/><b>{String.fromCharCode(65+i)}</b><input value={choice} placeholder={`Choice ${i+1}`} onChange={e=>updateChoice(i,e.target.value)} required/></label>)}</div>}
      {type==='true_false'&&<fieldset className="full"><legend>Correct answer</legend><div className="segmented"><button type="button" className={answer==='true'?'active':''} onClick={()=>setAnswer('true')}>True</button><button type="button" className={answer==='false'?'active':''} onClick={()=>setAnswer('false')}>False</button></div></fieldset>}
      {(type==='numeric_answer'||type==='short_answer'||type==='fill_blank')&&<><label className="full">Correct answer<input value={answer} onChange={e=>setAnswer(e.target.value)} type={type==='numeric_answer'?'number':'text'} required/></label>{type!=='numeric_answer'&&<label className="full">Also accept <small>Separate alternatives with |</small><input value={accepted} onChange={e=>setAccepted(e.target.value)} placeholder="e.g. r theta | r*theta"/></label>}</>}
      {type==='matching'&&<div className="structured-editor full"><span>Matching pairs</span>{pairs.map((pair,index)=><div key={index}><input value={pair.left} onChange={e=>setPair(index,'left',e.target.value)} placeholder="Left item"/><span>→</span><input value={pair.right} onChange={e=>setPair(index,'right',e.target.value)} placeholder="Correct match"/></div>)}<button type="button" onClick={()=>setPairs([...pairs,{left:'',right:''}])}><Plus/>Add pair</button></div>}
      {type==='ordering'&&<label className="full">Items in correct order <small>One item per line</small><textarea rows={6} value={orderText} onChange={e=>setOrderText(e.target.value)} required/></label>}
      {type==='drag_drop'&&<div className="structured-editor full"><label>Zones <small>Comma separated</small><input value={zonesText} onChange={e=>setZonesText(e.target.value)} placeholder="Translation, Stretch, Reflection" required/></label><span>Items and correct zones</span>{dragItems.map((item,index)=><div key={index}><input value={item.text} onChange={e=>setDrag(index,'text',e.target.value)} placeholder="Item"/><span>→</span><input value={item.correctZone} onChange={e=>setDrag(index,'correctZone',e.target.value)} placeholder="Zone"/></div>)}<button type="button" onClick={()=>setDragItems([...dragItems,{text:'',correctZone:''}])}><Plus/>Add item</button></div>}
      <label className="full">Explanation<textarea rows={3} value={explanation} onChange={e=>setExplanation(e.target.value)} required/></label><label className="full">Tags <small>Comma separated</small><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="e.g. composite functions, no calculator"/></label></div><div className="sheet-actions"><button type="button" className="button tertiary" onClick={onClose}>Cancel</button><button className="button primary"><Check size={17}/>Save as draft</button></div></form></div>
}
